var nodes = [
{ id: "TRIFORCE", group: 0, label: "TRIFORCE", level: 1, color: "red" },
{ id: "FELLOWSHIP", group: 1, label: "FELLOWSHIP", level: 1, color: "red" },
{ id: "DRAGONS", group: 2, label: "DRAGONS", level: 1, color: "red" },
{ id: "DISCIPLES", group: 3, label: "DISCIPLES", level: 1, color: "red" },
{ id: "NINTENDO", group: 4, label: "NINTENDO", level: 1, color: "red" },
{ id: "FORREST GUMP", group: 5, label: "FORREST GUMP", level: 1, color: "red" },
{ id: "WIZARD", group: 6, label: "WIZARD", level: 1, color: "orange" },
{ id: "DWARVES", group: 7, label: "DWARVES", level: 1, color: "orange" },
{ id: "ARCHERS", group: 8, label: "ARCHERS", level: 1, color: "orange" },
{ id: "TRAINS", group: 9, label: "TRAINS", level: 1, color: "orange" },
{ id: "BOUNTY HUNTERS", group: 10, label: "BOUNTY HUNTERS", level: 1, color: "orange" },
{ id: "MAJOR ARCANA", group: 11, label: "MAJOR ARCANA", level: 1, color: "orange" },
{ id: "COINS", group: 12, label: "COINS", level: 1, color: "orange" },
{ id: "MUSHROOMS", group: 13, label: "MUSHROOMS", level: 1, color: "orange" },
{ id: "LAUREN FAUST", group: 14, label: "LAUREN FAUST", level: 1, color: "orange" },
{ id: "DISNEY & PIXAR", group: 15, label: "DISNEY & PIXAR", level: 1, color: "orange" },
{ id: "SPACE PROGRAMS", group: 16, label: "SPACE PROGRAMS", level: 1, color: "orange" },
{ id: "THE HUNGER GAMES", group: 17, label: "THE HUNGER GAMES", level: 1, color: "orange" },
{ id: "ANIMALS", group: 18, label: "ANIMALS", level: 1, color: "orange" },
{ id: "MIT", group: 19, label: "MIT", level: 1, color: "orange" },
{ id: "MAJOR ARCANA", group: 20, label: "MAJOR ARCANA", level: 1, color: "orange" },
{ id: "ROBERT PATTINSON CHARACTERS", group: 21, label: "ROBERT PATTINSON CHARACTERS", level: 1, color: "orange" },
{ id: "COLORFUL CHARACTERS", group: 22, label: "COLORFUL CHARACTERS", level: 1, color: "orange" },
{ id: "LITERATURE", group: 23, label: "LITERATURE", level: 1, color: "orange" },
{ id: "MY LITTLE PONY", group: 24, label: "MY LITTLE PONY", level: 1, color: "orange" },
{ id: "GREEK MYTHOLOGY", group: 25, label: "GREEK MYTHOLOGY", level: 1, color: "orange" },
{ id: "TIME TRAVEL", group: 26, label: "TIME TRAVEL", level: 1, color: "orange" },
{ id: "BIRDS", group: 27, label: "BIRDS", level: 1, color: "orange" },
{ id: "PIRATES", group: 28, label: "PIRATES", level: 1, color: "orange" },
{ id: "METALS", group: 29, label: "METALS", level: 1, color: "orange" },
{ id: "GANDALF", group: 30, label: "GANDALF", level: 1, color: "green" },
{ id: "GIMLI", group: 31, label: "GIMLI", level: 1, color: "green" },
{ id: "LEGOLAS", group: 32, label: "LEGOLAS", level: 1, color: "green" },
{ id: "DUMBLEDORE", group: 33, label: "DUMBLEDORE", level: 1, color: "green" },
{ id: "HERMIONE GRANGER", group: 34, label: "HERMIONE GRANGER", level: 1, color: "green" },
{ id: "SLEEPY", group: 35, label: "SLEEPY", level: 1, color: "green" },
{ id: "DOC", group: 36, label: "DOC", level: 1, color: "green" },
{ id: "GRUMPY", group: 37, label: "GRUMPY", level: 1, color: "green" },
{ id: "KATNISS EVERDEEN", group: 38, label: "KATNISS EVERDEEN", level: 1, color: "green" },
{ id: "ROBIN HOOD", group: 39, label: "ROBIN HOOD", level: 1, color: "green" },
{ id: "APOLLO", group: 40, label: "APOLLO", level: 1, color: "green" },
{ id: "GREEN ARROW", group: 41, label: "GREEN ARROW", level: 1, color: "green" },
{ id: "THOMAS", group: 42, label: "THOMAS", level: 1, color: "green" },
{ id: "JAMES", group: 43, label: "JAMES", level: 1, color: "green" },
{ id: "PERCY", group: 44, label: "PERCY", level: 1, color: "green" },
{ id: "SIR TOPHAM HATT", group: 45, label: "SIR TOPHAM HATT", level: 1, color: "green" },
{ id: "MARIO", group: 46, label: "MARIO", level: 1, color: "green" },
{ id: "SAMUS ARAN", group: 47, label: "SAMUS ARAN", level: 1, color: "green" },
{ id: "FOX", group: 48, label: "FOX", level: 1, color: "green" },
{ id: "BOBA FETT", group: 49, label: "BOBA FETT", level: 1, color: "green" },
{ id: "STAR WARS", group: 50, label: "STAR WARS", level: 1, color: "green" },
{ id: "STAR", group: 51, label: "STAR", level: 1, color: "green" },
{ id: "STAR TREK", group: 52, label: "STAR TREK", level: 1, color: "green" },
{ id: "DARTH VADER", group: 53, label: "DARTH VADER", level: 1, color: "green" },
{ id: "LUKE SKYWALKER", group: 54, label: "LUKE SKYWALKER", level: 1, color: "green" },
{ id: "JET BLACK", group: 55, label: "JET BLACK", level: 1, color: "green" },
{ id: "SPIKE SPIEGEL", group: 56, label: "SPIKE SPIEGEL", level: 1, color: "green" },
{ id: "FAYE VALENTINE", group: 57, label: "FAYE VALENTINE", level: 1, color: "green" },
{ id: "RICK DECKARD", group: 58, label: "RICK DECKARD", level: 1, color: "green" },
{ id: "JOHN WICK", group: 59, label: "JOHN WICK", level: 1, color: "green" },
{ id: "KEANU REEVES", group: 60, label: "KEANU REEVES", level: 1, color: "green" },
{ id: "NEO", group: 61, label: "NEO", level: 1, color: "green" },
{ id: "THE MATRIX", group: 62, label: "THE MATRIX", level: 1, color: "green" },
{ id: "TED", group: 63, label: "TED", level: 1, color: "green" },
{ id: "BILL AND TED", group: 64, label: "BILL AND TED", level: 1, color: "green" },
{ id: "REVOLUTIONS", group: 65, label: "REVOLUTIONS", level: 1, color: "green" },
{ id: "RESURRECTIONS", group: 66, label: "RESURRECTIONS", level: 1, color: "green" },
{ id: "TRINITY", group: 67, label: "TRINITY", level: 1, color: "green" },
{ id: "MORPHEUS", group: 68, label: "MORPHEUS", level: 1, color: "green" },
{ id: "FATHER", group: 69, label: "FATHER", level: 1, color: "green" },
{ id: "SON", group: 70, label: "SON", level: 1, color: "green" },
{ id: "HOLY SPIRIT", group: 71, label: "HOLY SPIRIT", level: 1, color: "green" },
{ id: "DAUGHTER", group: 72, label: "DAUGHTER", level: 1, color: "green" },
{ id: "MOTHER", group: 73, label: "MOTHER", level: 1, color: "green" },
{ id: "AMERICA", group: 74, label: "AMERICA", level: 1, color: "green" },
{ id: "FRANCE", group: 75, label: "FRANCE", level: 1, color: "green" },
{ id: "RUSSIA", group: 76, label: "RUSSIA", level: 1, color: "green" },
{ id: "HAITI", group: 77, label: "HAITI", level: 1, color: "green" },
{ id: "BACK TO THE FUTURE", group: 78, label: "BACK TO THE FUTURE", level: 1, color: "green" },
{ id: "DOC BROWN", group: 79, label: "DOC BROWN", level: 1, color: "green" },
{ id: "COWBOY BEBOP", group: 80, label: "COWBOY BEBOP", level: 1, color: "green" },
{ id: "HIPPO", group: 81, label: "HIPPO", level: 1, color: "green" },
{ id: "PENNY", group: 82, label: "PENNY", level: 1, color: "green" },
{ id: "QUARTER", group: 83, label: "QUARTER", level: 1, color: "green" },
{ id: "NICKEL", group: 84, label: "NICKEL", level: 1, color: "green" },
{ id: "SUN", group: 85, label: "SUN", level: 1, color: "green" },
{ id: "SIRIUS", group: 86, label: "SIRIUS", level: 1, color: "green" },
{ id: "PERCY WEASLEY", group: 87, label: "PERCY WEASLEY", level: 1, color: "green" },
{ id: "SIRIUS BLACK", group: 88, label: "SIRIUS BLACK", level: 1, color: "green" },
{ id: "BELLATRIX BLACK", group: 89, label: "BELLATRIX BLACK", level: 1, color: "green" },
{ id: "MERLIN", group: 90, label: "MERLIN", level: 1, color: "green" },
{ id: "CEDRIC DIGGORY", group: 91, label: "CEDRIC DIGGORY", level: 1, color: "green" },
{ id: "BATMAN", group: 92, label: "BATMAN", level: 1, color: "green" },
{ id: "EDWARD CULLEN", group: 93, label: "EDWARD CULLEN", level: 1, color: "green" },
{ id: "BLACK", group: 94, label: "BLACK", level: 1, color: "green" },
{ id: "JACOB BLACK", group: 95, label: "JACOB BLACK", level: 1, color: "green" },
{ id: "SPIKE", group: 96, label: "SPIKE", level: 1, color: "green" },
{ id: "APPLEJACK", group: 97, label: "APPLEJACK", level: 1, color: "green" },
{ id: "APPLES", group: 98, label: "APPLES", level: 1, color: "green" },
{ id: "TWILIGHT SPARKLE", group: 99, label: "TWILIGHT SPARKLE", level: 1, color: "green" },
{ id: "PRINCESS LUNA", group: 100, label: "PRINCESS LUNA", level: 1, color: "green" },
{ id: "PRINCESS CELESTIA", group: 101, label: "PRINCESS CELESTIA", level: 1, color: "green" },
{ id: "MOON", group: 102, label: "MOON", level: 1, color: "green" },
{ id: "PRINCESS", group: 103, label: "PRINCESS", level: 1, color: "green" },
{ id: "TWILIGHT", group: 104, label: "TWILIGHT", level: 1, color: "green" },
{ id: "BELLA SWAN", group: 105, label: "BELLA SWAN", level: 1, color: "green" },
{ id: "VAMPIRE", group: 106, label: "VAMPIRE", level: 1, color: "green" },
{ id: "WEREWOLF", group: 107, label: "WEREWOLF", level: 1, color: "green" },
{ id: "NEW MOON", group: 108, label: "NEW MOON", level: 1, color: "green" },
{ id: "ECLIPSE", group: 109, label: "ECLIPSE", level: 1, color: "green" },
{ id: "WHEEL OF FORTUNE", group: 110, label: "WHEEL OF FORTUNE", level: 1, color: "green" },
{ id: "WORLD", group: 111, label: "WORLD", level: 1, color: "green" },
{ id: "FORTUNE", group: 112, label: "FORTUNE", level: 1, color: "green" },
{ id: "MUSHU", group: 113, label: "MUSHU", level: 1, color: "green" },
{ id: "SNOW WHITE", group: 114, label: "SNOW WHITE", level: 1, color: "green" },
{ id: "MERCURY", group: 115, label: "MERCURY", level: 1, color: "green" },
{ id: "GEMINI", group: 116, label: "GEMINI", level: 1, color: "green" },
{ id: "MOCKINGJAY", group: 117, label: "MOCKINGJAY", level: 1, color: "green" },
{ id: "PRESIDENT SNOW", group: 118, label: "PRESIDENT SNOW", level: 1, color: "green" },
{ id: "PEETA", group: 119, label: "PEETA", level: 1, color: "green" },
{ id: "POWER", group: 120, label: "POWER", level: 1, color: "green" },
{ id: "COURAGE", group: 121, label: "COURAGE", level: 1, color: "green" },
{ id: "WISDOM", group: 122, label: "WISDOM", level: 1, color: "green" },
{ id: "DND STATS", group: 123, label: "DND STATS", level: 1, color: "green" },
{ id: "STRENGTH", group: 124, label: "STRENGTH", level: 1, color: "green" },
{ id: "INTELLIGENCE", group: 125, label: "INTELLIGENCE", level: 1, color: "green" },
{ id: "CONSTITUTION", group: 126, label: "CONSTITUTION", level: 1, color: "green" },
{ id: "POWERPUFF GIRLS", group: 127, label: "POWERPUFF GIRLS", level: 1, color: "green" },
{ id: "BUTTERCUP", group: 128, label: "BUTTERCUP", level: 1, color: "green" },
{ id: "BUBBLES", group: 129, label: "BUBBLES", level: 1, color: "green" },
{ id: "BLOSSOM", group: 130, label: "BLOSSOM", level: 1, color: "green" },
{ id: "MOJO JOJO", group: 131, label: "MOJO JOJO", level: 1, color: "green" },
{ id: "PUFF", group: 132, label: "PUFF", level: 1, color: "green" },
{ id: "PUFF THE MAGIC DRAGON", group: 133, label: "PUFF THE MAGIC DRAGON", level: 1, color: "green" },
{ id: "DC SUPER HERO GIRLS", group: 134, label: "DC SUPER HERO GIRLS", level: 1, color: "green" },
{ id: "WONDER WOMAN", group: 135, label: "WONDER WOMAN", level: 1, color: "green" },
{ id: "BATGIRL", group: 136, label: "BATGIRL", level: 1, color: "green" },
{ id: "ZATANNA", group: 137, label: "ZATANNA", level: 1, color: "green" },
{ id: "SUPERGIRL", group: 138, label: "SUPERGIRL", level: 1, color: "green" },
{ id: "DC", group: 139, label: "DC", level: 1, color: "green" },
{ id: "SUPERMAN", group: 140, label: "SUPERMAN", level: 1, color: "green" },
{ id: "ROBIN", group: 141, label: "ROBIN", level: 1, color: "green" },
{ id: "SPARROW", group: 142, label: "SPARROW", level: 1, color: "green" },
{ id: "CARDINAL", group: 143, label: "CARDINAL", level: 1, color: "green" },
{ id: "JACK SPARROW", group: 144, label: "JACK SPARROW", level: 1, color: "green" },
{ id: "JACK", group: 145, label: "JACK", level: 1, color: "green" },
{ id: "DAVY JONES", group: 146, label: "DAVY JONES", level: 1, color: "green" },
{ id: "BLACKBEARD", group: 147, label: "BLACKBEARD", level: 1, color: "green" },
{ id: "CAPTAIN HOOK", group: 148, label: "CAPTAIN HOOK", level: 1, color: "green" },
{ id: "LUFFY", group: 149, label: "LUFFY", level: 1, color: "green" },
{ id: "LONG JOHN SILVER", group: 150, label: "LONG JOHN SILVER", level: 1, color: "green" },
{ id: "ONE PIECE", group: 151, label: "ONE PIECE", level: 1, color: "green" },
{ id: "JACK BLACK", group: 152, label: "JACK BLACK", level: 1, color: "green" },
{ id: "SHAZAM", group: 153, label: "SHAZAM", level: 1, color: "green" },
{ id: "SOLOMON", group: 154, label: "SOLOMON", level: 1, color: "green" },
{ id: "HERCULES", group: 155, label: "HERCULES", level: 1, color: "green" },
{ id: "ATLAS", group: 156, label: "ATLAS", level: 1, color: "green" },
{ id: "ZEUS", group: 157, label: "ZEUS", level: 1, color: "green" },
{ id: "ACHILLES", group: 158, label: "ACHILLES", level: 1, color: "green" },
{ id: "ATHENA", group: 159, label: "ATHENA", level: 1, color: "green" },
{ id: "BRAVE NEW WORLD", group: 160, label: "BRAVE NEW WORLD", level: 1, color: "green" },
{ id: "FORTUNE FAVORS THE BOLD", group: 161, label: "FORTUNE FAVORS THE BOLD", level: 1, color: "green" },
{ id: "FORTUNE TELLING", group: 162, label: "FORTUNE TELLING", level: 1, color: "green" },
{ id: "FORTUNE COOKIE", group: 163, label: "FORTUNE COOKIE", level: 1, color: "green" },
{ id: "MAGICIAN", group: 164, label: "MAGICIAN", level: 1, color: "green" },
{ id: "SUPERPOWER", group: 165, label: "SUPERPOWER", level: 1, color: "green" },
{ id: "UNITED STATES", group: 166, label: "UNITED STATES", level: 1, color: "green" },
{ id: "MYSTERY HUNT", group: 167, label: "MYSTERY HUNT", level: 1, color: "green" },
{ id: "GREAT DOME", group: 168, label: "GREAT DOME", level: 1, color: "green" },
{ id: "STATA CENTER", group: 169, label: "STATA CENTER", level: 1, color: "green" },
{ id: "GREEN BUILDING", group: 170, label: "GREEN BUILDING", level: 1, color: "green" },
{ id: "KRESGE CENTER", group: 171, label: "KRESGE CENTER", level: 1, color: "green" },
{ id: "GREEN", group: 172, label: "GREEN", level: 1, color: "green" },
{ id: "PRINCESS BUTTERCUP", group: 173, label: "PRINCESS BUTTERCUP", level: 1, color: "green" },
{ id: "DYSTOPIA", group: 174, label: "DYSTOPIA", level: 1, color: "green" },
{ id: "TIN", group: 175, label: "TIN", level: 1, color: "green" },
{ id: "SILVER", group: 176, label: "SILVER", level: 1, color: "green" },
{ id: "GOLD", group: 177, label: "GOLD", level: 1, color: "green" },
{ id: "TIN MAN", group: 178, label: "TIN MAN", level: 1, color: "green" },
{ id: "THE WIZARD OF OZ", group: 179, label: "THE WIZARD OF OZ", level: 1, color: "green" },
{ id: "DOROTHY GALE", group: 180, label: "DOROTHY GALE", level: 1, color: "green" },
{ id: "COWARDLY LION", group: 181, label: "COWARDLY LION", level: 1, color: "green" },
{ id: "PENNY PARK", group: 182, label: "PENNY PARK", level: 1, color: "green" },
{ id: "BOOKSPACE", group: 183, label: "BOOKSPACE", level: 1, color: "green" },
{ id: "PERPIW", group: 184, label: "PERPIW", level: 1, color: "green" },
{ id: "HOLIDAY FOREST", group: 185, label: "HOLIDAY FOREST", level: 1, color: "green" },
{ id: "VALENTINES DAY", group: 186, label: "VALENTINES DAY", level: 1, color: "green" },
{ id: "THANKSGIVING", group: 187, label: "THANKSGIVING", level: 1, color: "green" },
{ id: "VALENTINE", group: 188, label: "VALENTINE", level: 1, color: "green" },
{ id: "BOX OF CHOCOLATES", group: 189, label: "BOX OF CHOCOLATES", level: 1, color: "green" },
{ id: "TOM HANKS", group: 190, label: "TOM HANKS", level: 1, color: "green" },
{ id: "VIETNAM", group: 191, label: "VIETNAM", level: 1, color: "green" },
{ id: "THE GREEN MILE", group: 192, label: "THE GREEN MILE", level: 1, color: "green" },
{ id: "TOY STORY", group: 193, label: "TOY STORY", level: 1, color: "green" },
{ id: "PETER PAN", group: 194, label: "PETER PAN", level: 1, color: "green" },
{ id: "KANSAS", group: 195, label: "KANSAS", level: 1, color: "green" },
{ id: "TOTO", group: 196, label: "TOTO", level: 1, color: "green" },
{ id: "AFRICA", group: 197, label: "AFRICA", level: 1, color: "green" },
{ id: "HOLD THE LINE", group: 198, label: "HOLD THE LINE", level: 1, color: "green" },
]

var links = [
{ target: "FELLOWSHIP", source: "GANDALF", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "FELLOWSHIP", source: "GIMLI", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "FELLOWSHIP", source: "LEGOLAS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "GANDALF", source: "WIZARD", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "DUMBLEDORE", source: "WIZARD", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "HERMIONE GRANGER", source: "WIZARD", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "GIMLI", source: "DWARVES", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SLEEPY", source: "DWARVES", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "DOC", source: "DWARVES", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "GRUMPY", source: "DWARVES", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "LEGOLAS", source: "ARCHERS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "KATNISS EVERDEEN", source: "ARCHERS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "ROBIN HOOD", source: "ARCHERS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "APOLLO", source: "ARCHERS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "GREEN ARROW", source: "ARCHERS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "THOMAS", source: "DISCIPLES", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "JAMES", source: "DISCIPLES", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "THOMAS", source: "TRAINS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "JAMES", source: "TRAINS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "PERCY", source: "TRAINS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SIR TOPHAM HATT", source: "TRAINS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "MARIO", source: "NINTENDO", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SAMUS ARAN", source: "NINTENDO", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "FOX", source: "NINTENDO", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SAMUS ARAN", source: "BOUNTY HUNTERS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "BOBA FETT", source: "BOUNTY HUNTERS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "STAR WARS", source: "BOBA FETT", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "STAR", source: "MAJOR ARCANA", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "STAR TREK", source: "STAR", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "STAR WARS", source: "STAR", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "BOBA FETT", source: "STAR WARS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "DARTH VADER", source: "STAR WARS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "LUKE SKYWALKER", source: "STAR WARS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "LUKE SKYWALKER", source: "DARTH VADER", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "JET BLACK", source: "BOUNTY HUNTERS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SPIKE SPIEGEL", source: "BOUNTY HUNTERS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "FAYE VALENTINE", source: "BOUNTY HUNTERS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "RICK DECKARD", source: "BOUNTY HUNTERS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "JOHN WICK", source: "BOUNTY HUNTERS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "KEANU REEVES", source: "JOHN WICK", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "NEO", source: "KEANU REEVES", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "THE MATRIX", source: "NEO", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "TED", source: "KEANU REEVES", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "BILL AND TED", source: "TED", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "REVOLUTIONS", source: "THE MATRIX", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "RESURRECTIONS", source: "THE MATRIX", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "TRINITY", source: "THE MATRIX", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "MORPHEUS", source: "THE MATRIX", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "FATHER", source: "TRINITY", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SON", source: "TRINITY", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "HOLY SPIRIT", source: "TRINITY", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "DAUGHTER", source: "SON", color: "red", strength: 0.3 },
{ target: "MOTHER", source: "FATHER", color: "red", strength: 0.3 },
{ target: "AMERICA", source: "REVOLUTIONS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "FRANCE", source: "REVOLUTIONS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "RUSSIA", source: "REVOLUTIONS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "HAITI", source: "REVOLUTIONS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "BILL AND TED", source: "TIME TRAVEL", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "BACK TO THE FUTURE", source: "TIME TRAVEL", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "DOC BROWN", source: "BACK TO THE FUTURE", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "DOC", source: "DOC BROWN", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "JET BLACK", source: "COWBOY BEBOP", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SPIKE SPIEGEL", source: "COWBOY BEBOP", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "FAYE VALENTINE", source: "COWBOY BEBOP", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "FOX", source: "ANIMALS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "HIPPO", source: "ANIMALS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "MUSHROOMS", source: "MARIO", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "STAR", source: "MARIO", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "COINS", source: "MARIO", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "PENNY", source: "COINS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "QUARTER", source: "COINS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "NICKEL", source: "COINS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SUN", source: "STAR", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SIRIUS", source: "STAR", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "PERCY WEASLEY", source: "WIZARD", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "PERCY", source: "PERCY WEASLEY", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SIRIUS BLACK", source: "SIRIUS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SIRIUS BLACK", source: "WIZARD", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "BELLATRIX BLACK", source: "WIZARD", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "MERLIN", source: "WIZARD", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "CEDRIC DIGGORY", source: "WIZARD", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "ROBERT PATTINSON CHARACTERS", source: "CEDRIC DIGGORY", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "BATMAN", source: "ROBERT PATTINSON CHARACTERS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "EDWARD CULLEN", source: "ROBERT PATTINSON CHARACTERS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SIRIUS BLACK", source: "BLACK", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "JACOB BLACK", source: "BLACK", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "JET BLACK", source: "BLACK", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "BELLATRIX BLACK", source: "BLACK", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SPIKE", source: "MY LITTLE PONY", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "APPLEJACK", source: "MY LITTLE PONY", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "APPLEJACK", source: "APPLES", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "TWILIGHT SPARKLE", source: "MY LITTLE PONY", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "PRINCESS LUNA", source: "MY LITTLE PONY", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "PRINCESS CELESTIA", source: "MY LITTLE PONY", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SUN", source: "PRINCESS CELESTIA", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "MOON", source: "PRINCESS LUNA", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "PRINCESS", source: "PRINCESS CELESTIA", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "PRINCESS", source: "PRINCESS LUNA", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "TWILIGHT", source: "TWILIGHT SPARKLE", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "EDWARD CULLEN", source: "TWILIGHT", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "BELLA SWAN", source: "TWILIGHT", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "JACOB BLACK", source: "TWILIGHT", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "VAMPIRE", source: "TWILIGHT", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "WEREWOLF", source: "TWILIGHT", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "NEW MOON", source: "TWILIGHT", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "ECLIPSE", source: "TWILIGHT", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SUN", source: "ECLIPSE", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "MOON", source: "ECLIPSE", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "MOON", source: "SUN", color: "red", strength: 0.3 },
{ target: "MOON", source: "NEW MOON", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "MOON", source: "MAJOR ARCANA", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "WHEEL OF FORTUNE", source: "MAJOR ARCANA", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "WORLD", source: "MAJOR ARCANA", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "WHEEL OF FORTUNE", source: "FORTUNE", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SPIKE SPIEGEL", source: "SPIKE", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SPIKE", source: "DRAGONS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "MUSHU", source: "DRAGONS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "MUSHU", source: "DISNEY & PIXAR", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SNOW WHITE", source: "DISNEY & PIXAR", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SLEEPY", source: "SNOW WHITE", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "GRUMPY", source: "SNOW WHITE", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "APOLLO", source: "SPACE PROGRAMS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "MERCURY", source: "SPACE PROGRAMS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "GEMINI", source: "SPACE PROGRAMS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "MOCKINGJAY", source: "ANIMALS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "MOCKINGJAY", source: "THE HUNGER GAMES", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "PRESIDENT SNOW", source: "THE HUNGER GAMES", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "PEETA", source: "THE HUNGER GAMES", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "POWER", source: "TRIFORCE", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "COURAGE", source: "TRIFORCE", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "WISDOM", source: "TRIFORCE", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "STRENGTH", source: "DND STATS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "WISDOM", source: "DND STATS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "INTELLIGENCE", source: "DND STATS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "CONSTITUTION", source: "DND STATS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "POWERPUFF GIRLS", source: "POWER", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "POWERPUFF GIRLS", source: "BUTTERCUP", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "POWERPUFF GIRLS", source: "BUBBLES", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "POWERPUFF GIRLS", source: "BLOSSOM", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "POWERPUFF GIRLS", source: "MOJO JOJO", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "POWERPUFF GIRLS", source: "LAUREN FAUST", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "PUFF", source: "POWERPUFF GIRLS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "PUFF THE MAGIC DRAGON", source: "PUFF", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "PUFF THE MAGIC DRAGON", source: "DRAGONS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "MY LITTLE PONY", source: "LAUREN FAUST", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "DC SUPER HERO GIRLS", source: "LAUREN FAUST", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "WONDER WOMAN", source: "DC SUPER HERO GIRLS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "BATGIRL", source: "DC SUPER HERO GIRLS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "ZATANNA", source: "DC SUPER HERO GIRLS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SUPERGIRL", source: "DC SUPER HERO GIRLS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "WONDER WOMAN", source: "DC", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "BATGIRL", source: "DC", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "ZATANNA", source: "DC", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SUPERGIRL", source: "DC", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SUPERMAN", source: "DC", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SUPERGIRL", source: "SUPERMAN", color: "red", strength: 0.3 },
{ target: "BATGIRL", source: "BATMAN", color: "red", strength: 0.3 },
{ target: "ROBIN", source: "BATMAN", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "BIRDS", source: "ROBIN", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SPARROW", source: "BIRDS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "CARDINAL", source: "BIRDS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "JACK SPARROW", source: "SPARROW", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "JACK", source: "JACK SPARROW", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "PIRATES", source: "JACK SPARROW", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "DAVY JONES", source: "PIRATES", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "BLACKBEARD", source: "PIRATES", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "CAPTAIN HOOK", source: "PIRATES", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "LUFFY", source: "PIRATES", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "LONG JOHN SILVER", source: "PIRATES", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "ONE PIECE", source: "LUFFY", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "JACK BLACK", source: "JACK", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "JACK BLACK", source: "BLACK", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "BATMAN", source: "DC", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "BATMAN", source: "BATGIRL", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SHAZAM", source: "DC", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SOLOMON", source: "SHAZAM", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "HERCULES", source: "SHAZAM", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "ATLAS", source: "SHAZAM", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "WORLD", source: "ATLAS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "ZEUS", source: "SHAZAM", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "ACHILLES", source: "SHAZAM", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "MERCURY", source: "SHAZAM", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "ACHILLES", source: "GREEK MYTHOLOGY", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "ZEUS", source: "GREEK MYTHOLOGY", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "HERCULES", source: "GREEK MYTHOLOGY", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "ATHENA", source: "GREEK MYTHOLOGY", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "ATHENA", source: "MIT", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "ATHENA", source: "WISDOM", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SOLOMON", source: "WISDOM", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "BRAVE NEW WORLD", source: "COURAGE", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "FORTUNE FAVORS THE BOLD", source: "COURAGE", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "FORTUNE FAVORS THE BOLD", source: "FORTUNE", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "FORTUNE TELLING", source: "FORTUNE", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "FORTUNE COOKIE", source: "FORTUNE", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "MAJOR ARCANA", source: "FORTUNE TELLING", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "STRENGTH", source: "MAJOR ARCANA", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "MAGICIAN", source: "MAJOR ARCANA", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SUN", source: "MAJOR ARCANA", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "WIZARD", source: "MAGICIAN", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SUPERPOWER", source: "POWER", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "UNITED STATES", source: "SUPERPOWER", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SUPERMAN", source: "SUPERPOWER", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "MYSTERY HUNT", source: "MIT", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "GREAT DOME", source: "MIT", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "STATA CENTER", source: "MIT", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "GREEN BUILDING", source: "MIT", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "KRESGE CENTER", source: "MIT", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "GREEN BUILDING", source: "GREEN", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "GREEN ARROW", source: "GREEN", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "PRINCESS BUTTERCUP", source: "BUTTERCUP", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "PRINCESS", source: "PRINCESS BUTTERCUP", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "BRAVE NEW WORLD", source: "LITERATURE", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "TWILIGHT", source: "LITERATURE", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "THE HUNGER GAMES", source: "DYSTOPIA", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "GREEN ARROW", source: "COLORFUL CHARACTERS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SNOW WHITE", source: "COLORFUL CHARACTERS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "DOC BROWN", source: "COLORFUL CHARACTERS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "NICKEL", source: "METALS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "TIN", source: "METALS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "SILVER", source: "METALS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "GOLD", source: "METALS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "LONG JOHN SILVER", source: "SILVER", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "TIN MAN", source: "TIN", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "THE WIZARD OF OZ", source: "TIN MAN", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "THE WIZARD OF OZ", source: "WIZARD", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "THE WIZARD OF OZ", source: "DOROTHY GALE", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "THE WIZARD OF OZ", source: "COWARDLY LION", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "COURAGE", source: "COWARDLY LION", color: "red", strength: 0.3 },
{ target: "PENNY PARK", source: "PENNY", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "MYSTERY HUNT", source: "PENNY PARK", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "BOOKSPACE", source: "MYSTERY HUNT", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "LITERATURE", source: "BOOKSPACE", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "PERPIW", source: "MYSTERY HUNT", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "HOLIDAY FOREST", source: "MYSTERY HUNT", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "VALENTINES DAY", source: "HOLIDAY FOREST", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "THANKSGIVING", source: "HOLIDAY FOREST", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "VALENTINE", source: "VALENTINES DAY", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "FAYE VALENTINE", source: "VALENTINE", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "BRAVE NEW WORLD", source: "WORLD", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "BOX OF CHOCOLATES", source: "VALENTINES DAY", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "BOX OF CHOCOLATES", source: "FORREST GUMP", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "TOM HANKS", source: "FORREST GUMP", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "VIETNAM", source: "FORREST GUMP", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "APOLLO", source: "TOM HANKS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "THE GREEN MILE", source: "TOM HANKS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "THE GREEN MILE", source: "GREEN", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "TOY STORY", source: "DISNEY & PIXAR", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "PETER PAN", source: "DISNEY & PIXAR", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "CAPTAIN HOOK", source: "PETER PAN", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "TOY STORY", source: "TOM HANKS", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "KANSAS", source: "DOROTHY GALE", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "TOTO", source: "DOROTHY GALE", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "AFRICA", source: "TOTO", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
{ target: "HOLD THE LINE", source: "TOTO", color: "rgba(50, 50, 50, 0.5)", strength: 0.3 },
]
