var nodes = [
{ id: "TRIFORCE", group: 0, label: "TRIFORCE", level: 1, color: "pink" },
{ id: "APOSTLE", group: 1, label: "APOSTLE", level: 1, color: "red" },
{ id: "APPLE", group: 2, label: "APPLE", level: 1, color: "red" },
{ id: "ARABIAN NIGHTS", group: 3, label: "ARABIAN NIGHTS", level: 1, color: "red" },
{ id: "DRAGON", group: 4, label: "DRAGON", level: 1, color: "red" },
{ id: "FELLOWSHIP", group: 5, label: "FELLOWSHIP", level: 1, color: "red" },
{ id: "ALI BABA", group: 6, label: "ALI BABA", level: 1, color: "green" },
{ id: "FACEBOOK", group: 7, label: "FACEBOOK", level: 1, color: "green" },
{ id: "NINETEEN EIGHTY-FOUR", group: 8, label: "NINETEEN EIGHTY-FOUR", level: 1, color: "green" },
{ id: "TENCENT", group: 9, label: "TENCENT", level: 1, color: "green" },
{ id: "THOMAS THE TANK ENGINE", group: 10, label: "THOMAS THE TANK ENGINE", level: 1, color: "green" },
{ id: "UNITED STATES", group: 11, label: "UNITED STATES", level: 1, color: "green" },
{ id: "ARCHER", group: 12, label: "ARCHER", level: 1, color: "orange" },
{ id: "ASTROLOGY", group: 13, label: "ASTROLOGY", level: 1, color: "orange" },
{ id: "BIRD", group: 14, label: "BIRD", level: 1, color: "orange" },
{ id: "DC", group: 15, label: "DC", level: 1, color: "orange" },
{ id: "DISNEY", group: 16, label: "DISNEY", level: 1, color: "orange" },
{ id: "DWARF", group: 17, label: "DWARF", level: 1, color: "orange" },
{ id: "DYSTOPIA", group: 18, label: "DYSTOPIA", level: 1, color: "orange" },
{ id: "GREEK MYTHOLOGY", group: 19, label: "GREEK MYTHOLOGY", level: 1, color: "orange" },
{ id: "HASBRO", group: 20, label: "HASBRO", level: 1, color: "orange" },
{ id: "LOVE LETTER", group: 21, label: "LOVE LETTER", level: 1, color: "orange" },
{ id: "MAJOR ARCANA", group: 22, label: "MAJOR ARCANA", level: 1, color: "orange" },
{ id: "MEASUREMENT", group: 23, label: "MEASUREMENT", level: 1, color: "orange" },
{ id: "METAL", group: 24, label: "METAL", level: 1, color: "orange" },
{ id: "MIT", group: 25, label: "MIT", level: 1, color: "orange" },
{ id: "MY LITTLE PONY", group: 26, label: "MY LITTLE PONY", level: 1, color: "orange" },
{ id: "PIRATE", group: 27, label: "PIRATE", level: 1, color: "orange" },
{ id: "RESISTOR COLOR", group: 28, label: "RESISTOR COLOR", level: 1, color: "orange" },
{ id: "ROBERT PATTINSON", group: 29, label: "ROBERT PATTINSON", level: 1, color: "orange" },
{ id: "SESAME STREET", group: 30, label: "SESAME STREET", level: 1, color: "orange" },
{ id: "THE HUNGER GAMES", group: 31, label: "THE HUNGER GAMES", level: 1, color: "orange" },
{ id: "TWILIGHT", group: 32, label: "TWILIGHT", level: 1, color: "orange" },
{ id: "WIZARD", group: 33, label: "WIZARD", level: 1, color: "orange" },
{ id: "COIN", group: 34, label: "COIN", level: 1, color: "orange" },
{ id: "POWERPUFF GIRLS", group: 35, label: "POWERPUFF GIRLS", level: 1, color: "orange" },
{ id: "GENSHIN IMPACT", group: 36, label: "GENSHIN IMPACT", level: 1, color: "orange" },
{ id: "STARBUCKS", group: 37, label: "STARBUCKS", level: 1, color: "orange" },
{ id: "BARTHOLOMEW", group: 38, label: "BARTHOLOMEW", level: 1, color: "green" },
{ id: "WORLD", group: 39, label: "WORLD", level: 1, color: "green" },
{ id: "SIRIUS BLACK", group: 40, label: "SIRIUS BLACK", level: 1, color: "green" },
{ id: "BAIDU", group: 41, label: "BAIDU", level: 1, color: "green" },
{ id: "TECH COMPANY", group: 42, label: "TECH COMPANY", level: 1, color: "green" },
{ id: "ELF", group: 43, label: "ELF", level: 1, color: "green" },
{ id: "LEGOLAS", group: 44, label: "LEGOLAS", level: 1, color: "green" },
{ id: "MIT MYSTERY HUNT", group: 45, label: "MIT MYSTERY HUNT", level: 1, color: "green" },
{ id: "PENNY PARK", group: 46, label: "PENNY PARK", level: 1, color: "green" },
{ id: "BROWN", group: 47, label: "BROWN", level: 1, color: "green" },
{ id: "QUARTER", group: 48, label: "QUARTER", level: 1, color: "green" },
{ id: "SILVER", group: 49, label: "SILVER", level: 1, color: "green" },
{ id: "ONE", group: 50, label: "ONE", level: 1, color: "green" },
{ id: "ONE PIECE", group: 51, label: "ONE PIECE", level: 1, color: "green" },
{ id: "MUSHU", group: 52, label: "MUSHU", level: 1, color: "green" },
{ id: "GO", group: 53, label: "GO", level: 1, color: "green" },
{ id: "MONOPOLY", group: 54, label: "MONOPOLY", level: 1, color: "green" },
{ id: "NUMBER", group: 55, label: "NUMBER", level: 1, color: "green" },
{ id: "DC SUPER HERO GIRLS", group: 56, label: "DC SUPER HERO GIRLS", level: 1, color: "green" },
{ id: "ZATANNA", group: 57, label: "ZATANNA", level: 1, color: "green" },
{ id: "JOHN LENNON", group: 58, label: "JOHN LENNON", level: 1, color: "green" },
{ id: "STRAWBERRY FIELDS", group: 59, label: "STRAWBERRY FIELDS", level: 1, color: "green" },
{ id: "GO TO JAIL", group: 60, label: "GO TO JAIL", level: 1, color: "green" },
{ id: "ROBIN HOOD", group: 61, label: "ROBIN HOOD", level: 1, color: "green" },
{ id: "VENTI", group: 62, label: "VENTI", level: 1, color: "green" },
{ id: "LEO", group: 63, label: "LEO", level: 1, color: "green" },
{ id: "XIAOMI", group: 64, label: "XIAOMI", level: 1, color: "green" },
{ id: "BUTTERCUP", group: 65, label: "BUTTERCUP", level: 1, color: "green" },
{ id: "GREAT DOME", group: 66, label: "GREAT DOME", level: 1, color: "green" },
{ id: "GIRL", group: 67, label: "GIRL", level: 1, color: "green" },
{ id: "BLACK", group: 68, label: "BLACK", level: 1, color: "green" },
{ id: "POKEMON GO", group: 69, label: "POKEMON GO", level: 1, color: "green" },
{ id: "VALOR", group: 70, label: "VALOR", level: 1, color: "green" },
{ id: "DUNGEONS & DRAGONS", group: 71, label: "DUNGEONS & DRAGONS", level: 1, color: "green" },
{ id: "PUFF THE MAGIC DRAGON", group: 72, label: "PUFF THE MAGIC DRAGON", level: 1, color: "green" },
{ id: "CEDRIC DIGGORY", group: 73, label: "CEDRIC DIGGORY", level: 1, color: "green" },
{ id: "PENNY", group: 74, label: "PENNY", level: 1, color: "green" },
{ id: "SAM", group: 75, label: "SAM", level: 1, color: "green" },
{ id: "KEANU REEVES", group: 76, label: "KEANU REEVES", level: 1, color: "green" },
{ id: "NEO", group: 77, label: "NEO", level: 1, color: "green" },
{ id: "SESAME", group: 78, label: "SESAME", level: 1, color: "green" },
{ id: "PRESIDENT SNOW", group: 79, label: "PRESIDENT SNOW", level: 1, color: "green" },
{ id: "PRIEST", group: 80, label: "PRIEST", level: 1, color: "green" },
{ id: "MERCURY", group: 81, label: "MERCURY", level: 1, color: "green" },
{ id: "SHAZAM", group: 82, label: "SHAZAM", level: 1, color: "green" },
{ id: "FRODO", group: 83, label: "FRODO", level: 1, color: "green" },
{ id: "HOBBIT", group: 84, label: "HOBBIT", level: 1, color: "green" },
{ id: "PETER", group: 85, label: "PETER", level: 1, color: "green" },
{ id: "PETER PAN", group: 86, label: "PETER PAN", level: 1, color: "green" },
{ id: "LONG JOHN SILVER", group: 87, label: "LONG JOHN SILVER", level: 1, color: "green" },
{ id: "PERCY", group: 88, label: "PERCY", level: 1, color: "green" },
{ id: "SIR TOPHAM HATT", group: 89, label: "SIR TOPHAM HATT", level: 1, color: "green" },
{ id: "MAYFLOWER", group: 90, label: "MAYFLOWER", level: 1, color: "green" },
{ id: "SIRIUS", group: 91, label: "SIRIUS", level: 1, color: "green" },
{ id: "STAR", group: 92, label: "STAR", level: 1, color: "green" },
{ id: "DOROTHY GALE", group: 93, label: "DOROTHY GALE", level: 1, color: "green" },
{ id: "THE WIZARD OF OZ", group: 94, label: "THE WIZARD OF OZ", level: 1, color: "green" },
{ id: "SPACE PROGRAM", group: 95, label: "SPACE PROGRAM", level: 1, color: "green" },
{ id: "BIG BIRD", group: 96, label: "BIG BIRD", level: 1, color: "green" },
{ id: "THE LORD OF THE RINGS", group: 97, label: "THE LORD OF THE RINGS", level: 1, color: "green" },
{ id: "PHILIP", group: 98, label: "PHILIP", level: 1, color: "green" },
{ id: "GALE", group: 99, label: "GALE", level: 1, color: "green" },
{ id: "SIMPSONS", group: 100, label: "SIMPSONS", level: 1, color: "green" },
{ id: "JESUS CHRIST", group: 101, label: "JESUS CHRIST", level: 1, color: "green" },
{ id: "THE LAST SUPPER", group: 102, label: "THE LAST SUPPER", level: 1, color: "green" },
{ id: "FLOWER GIRL", group: 103, label: "FLOWER GIRL", level: 1, color: "green" },
{ id: "WEDDING", group: 104, label: "WEDDING", level: 1, color: "green" },
{ id: "DONATELLO", group: 105, label: "DONATELLO", level: 1, color: "green" },
{ id: "NINJA TURTLE", group: 106, label: "NINJA TURTLE", level: 1, color: "green" },
{ id: "ACHILLES", group: 107, label: "ACHILLES", level: 1, color: "green" },
{ id: "FRUIT", group: 108, label: "FRUIT", level: 1, color: "green" },
{ id: "ORANGE", group: 109, label: "ORANGE", level: 1, color: "green" },
{ id: "HERCULES", group: 110, label: "HERCULES", level: 1, color: "green" },
{ id: "BRAVE NEW WORLD", group: 111, label: "BRAVE NEW WORLD", level: 1, color: "green" },
{ id: "NEIL", group: 112, label: "NEIL", level: 1, color: "green" },
{ id: "FLOWER", group: 113, label: "FLOWER", level: 1, color: "green" },
{ id: "FLOWER POWER", group: 114, label: "FLOWER POWER", level: 1, color: "green" },
{ id: "PIPPIN", group: 115, label: "PIPPIN", level: 1, color: "green" },
{ id: "JUDAS", group: 116, label: "JUDAS", level: 1, color: "green" },
{ id: "PERCY WEASLEY", group: 117, label: "PERCY WEASLEY", level: 1, color: "green" },
{ id: "BATMAN", group: 118, label: "BATMAN", level: 1, color: "green" },
{ id: "ROBIN", group: 119, label: "ROBIN", level: 1, color: "green" },
{ id: "ALADDIN", group: 120, label: "ALADDIN", level: 1, color: "green" },
{ id: "BATGIRL", group: 121, label: "BATGIRL", level: 1, color: "green" },
{ id: "PRINCESS CELESTIA", group: 122, label: "PRINCESS CELESTIA", level: 1, color: "green" },
{ id: "SUN", group: 123, label: "SUN", level: 1, color: "green" },
{ id: "PRINCESS", group: 124, label: "PRINCESS", level: 1, color: "green" },
{ id: "PRINCESS LUNA", group: 125, label: "PRINCESS LUNA", level: 1, color: "green" },
{ id: "GROOM", group: 126, label: "GROOM", level: 1, color: "green" },
{ id: "COMMUNITY CHEST", group: 127, label: "COMMUNITY CHEST", level: 1, color: "green" },
{ id: "ATHENA", group: 128, label: "ATHENA", level: 1, color: "green" },
{ id: "WISDOM", group: 129, label: "WISDOM", level: 1, color: "green" },
{ id: "SISTINE CHAPEL", group: 130, label: "SISTINE CHAPEL", level: 1, color: "green" },
{ id: "THE CREATION OF ADAM", group: 131, label: "THE CREATION OF ADAM", level: 1, color: "green" },
{ id: "JOHNNY APPLESEED", group: 132, label: "JOHNNY APPLESEED", level: 1, color: "green" },
{ id: "MOON", group: 133, label: "MOON", level: 1, color: "green" },
{ id: "COUNT VON COUNT", group: 134, label: "COUNT VON COUNT", level: 1, color: "green" },
{ id: "VAMPIRE", group: 135, label: "VAMPIRE", level: 1, color: "green" },
{ id: "COURAGE", group: 136, label: "COURAGE", level: 1, color: "green" },
{ id: "BOROMIR", group: 137, label: "BOROMIR", level: 1, color: "green" },
{ id: "SMOOT", group: 138, label: "SMOOT", level: 1, color: "green" },
{ id: "FORTUNE FAVORS THE BOLD", group: 139, label: "FORTUNE FAVORS THE BOLD", level: 1, color: "green" },
{ id: "PRINCE", group: 140, label: "PRINCE", level: 1, color: "green" },
{ id: "RED DELICIOUS", group: 141, label: "RED DELICIOUS", level: 1, color: "green" },
{ id: "SNOW", group: 142, label: "SNOW", level: 1, color: "green" },
{ id: "7 RINGS", group: 143, label: "7 RINGS", level: 1, color: "green" },
{ id: "RING", group: 144, label: "RING", level: 1, color: "green" },
{ id: "SMAUG", group: 145, label: "SMAUG", level: 1, color: "green" },
{ id: "GANDALF", group: 146, label: "GANDALF", level: 1, color: "green" },
{ id: "WHITE", group: 147, label: "WHITE", level: 1, color: "green" },
{ id: "MERLIN", group: 148, label: "MERLIN", level: 1, color: "green" },
{ id: "GROVER", group: 149, label: "GROVER", level: 1, color: "green" },
{ id: "PERPIW", group: 150, label: "PERPIW", level: 1, color: "green" },
{ id: "TIM THE BEAVER", group: 151, label: "TIM THE BEAVER", level: 1, color: "green" },
{ id: "MICHELANGELO", group: 152, label: "MICHELANGELO", level: 1, color: "green" },
{ id: "ECLIPSE", group: 153, label: "ECLIPSE", level: 1, color: "green" },
{ id: "EDWARD CULLEN", group: 154, label: "EDWARD CULLEN", level: 1, color: "green" },
{ id: "GOLD", group: 155, label: "GOLD", level: 1, color: "green" },
{ id: "DOC", group: 156, label: "DOC", level: 1, color: "green" },
{ id: "SNOW WHITE", group: 157, label: "SNOW WHITE", level: 1, color: "green" },
{ id: "BREAKING DAWN", group: 158, label: "BREAKING DAWN", level: 1, color: "green" },
{ id: "FORTUNE", group: 159, label: "FORTUNE", level: 1, color: "green" },
{ id: "FORTUNE TELLING", group: 160, label: "FORTUNE TELLING", level: 1, color: "green" },
{ id: "SLEEPY", group: 161, label: "SLEEPY", level: 1, color: "green" },
{ id: "WONDER WOMAN", group: 162, label: "WONDER WOMAN", level: 1, color: "green" },
{ id: "TED", group: 163, label: "TED", level: 1, color: "green" },
{ id: "BRASS", group: 164, label: "BRASS", level: 1, color: "green" },
{ id: "COPPER", group: 165, label: "COPPER", level: 1, color: "green" },
{ id: "JACOB BLACK", group: 166, label: "JACOB BLACK", level: 1, color: "green" },
{ id: "SAGITTARIUS", group: 167, label: "SAGITTARIUS", level: 1, color: "green" },
{ id: "ATLAS", group: 168, label: "ATLAS", level: 1, color: "green" },
{ id: "SPIKE", group: 169, label: "SPIKE", level: 1, color: "green" },
{ id: "CATHOLIC CHURCH", group: 170, label: "CATHOLIC CHURCH", level: 1, color: "green" },
{ id: "POPE", group: 171, label: "POPE", level: 1, color: "green" },
{ id: "OPEN SESAME", group: 172, label: "OPEN SESAME", level: 1, color: "green" },
{ id: "MOJO JOJO", group: 173, label: "MOJO JOJO", level: 1, color: "green" },
{ id: "BLUE-EYES WHITE DRAGON", group: 174, label: "BLUE-EYES WHITE DRAGON", level: 1, color: "green" },
{ id: "HALFLING", group: 175, label: "HALFLING", level: 1, color: "green" },
{ id: "TALL", group: 176, label: "TALL", level: 1, color: "green" },
{ id: "OSCAR", group: 177, label: "OSCAR", level: 1, color: "green" },
{ id: "BLOSSOM", group: 178, label: "BLOSSOM", level: 1, color: "green" },
{ id: "LAUREN FAUST", group: 179, label: "LAUREN FAUST", level: 1, color: "green" },
{ id: "DUMBLEDORE", group: 180, label: "DUMBLEDORE", level: 1, color: "green" },
{ id: "JOHN", group: 181, label: "JOHN", level: 1, color: "green" },
{ id: "JOHN WICK", group: 182, label: "JOHN WICK", level: 1, color: "green" },
{ id: "PRINCESS BUTTERCUP", group: 183, label: "PRINCESS BUTTERCUP", level: 1, color: "green" },
{ id: "THE PRINCESS BRIDE", group: 184, label: "THE PRINCESS BRIDE", level: 1, color: "green" },
{ id: "SUNFLOWER", group: 185, label: "SUNFLOWER", level: 1, color: "green" },
{ id: "ONE RING", group: 186, label: "ONE RING", level: 1, color: "green" },
{ id: "KING ARTHUR", group: 187, label: "KING ARTHUR", level: 1, color: "green" },
{ id: "BRIDE", group: 188, label: "BRIDE", level: 1, color: "green" },
{ id: "APOLLO", group: 189, label: "APOLLO", level: 1, color: "green" },
{ id: "BELLATRIX BLACK", group: 190, label: "BELLATRIX BLACK", level: 1, color: "green" },
{ id: "KATNISS EVERDEEN", group: 191, label: "KATNISS EVERDEEN", level: 1, color: "green" },
{ id: "FORTUNE COOKIE", group: 192, label: "FORTUNE COOKIE", level: 1, color: "green" },
{ id: "GEORGE WASHINGTON", group: 193, label: "GEORGE WASHINGTON", level: 1, color: "green" },
{ id: "JACK SPARROW", group: 194, label: "JACK SPARROW", level: 1, color: "green" },
{ id: "NICKEL", group: 195, label: "NICKEL", level: 1, color: "green" },
{ id: "ARIANA GRANDE", group: 196, label: "ARIANA GRANDE", level: 1, color: "green" },
{ id: "PUFF", group: 197, label: "PUFF", level: 1, color: "green" },
{ id: "LUFFY", group: 198, label: "LUFFY", level: 1, color: "green" },
{ id: "CONSTITUTION", group: 199, label: "CONSTITUTION", level: 1, color: "green" },
{ id: "DECLARATION OF INDEPENDENCE", group: 200, label: "DECLARATION OF INDEPENDENCE", level: 1, color: "green" },
{ id: "THREE", group: 201, label: "THREE", level: 1, color: "green" },
{ id: "COOKIE MONSTER", group: 202, label: "COOKIE MONSTER", level: 1, color: "green" },
{ id: "COWARDLY LION", group: 203, label: "COWARDLY LION", level: 1, color: "green" },
{ id: "LION", group: 204, label: "LION", level: 1, color: "green" },
{ id: "DRACULA", group: 205, label: "DRACULA", level: 1, color: "green" },
{ id: "BLUE", group: 206, label: "BLUE", level: 1, color: "green" },
{ id: "BYTEDANCE", group: 207, label: "BYTEDANCE", level: 1, color: "green" },
{ id: "GRANDE", group: 208, label: "GRANDE", level: 1, color: "green" },
{ id: "HANDMAID", group: 209, label: "HANDMAID", level: 1, color: "green" },
{ id: "THE HANDMAID'S TALE", group: 210, label: "THE HANDMAID'S TALE", level: 1, color: "green" },
{ id: "TIN MAN", group: 211, label: "TIN MAN", level: 1, color: "green" },
{ id: "DOC BROWN", group: 212, label: "DOC BROWN", level: 1, color: "green" },
{ id: "MAGIC THE GATHERING", group: 213, label: "MAGIC THE GATHERING", level: 1, color: "green" },
{ id: "SUPERMAN", group: 214, label: "SUPERMAN", level: 1, color: "green" },
{ id: "KRESGE CENTER", group: 215, label: "KRESGE CENTER", level: 1, color: "green" },
{ id: "ERNIE", group: 216, label: "ERNIE", level: 1, color: "green" },
{ id: "GREEN", group: 217, label: "GREEN", level: 1, color: "green" },
{ id: "EVERYTHING NICE", group: 218, label: "EVERYTHING NICE", level: 1, color: "green" },
{ id: "GIMLI", group: 219, label: "GIMLI", level: 1, color: "green" },
{ id: "MARGE", group: 220, label: "MARGE", level: 1, color: "green" },
{ id: "FREE PARKING", group: 221, label: "FREE PARKING", level: 1, color: "green" },
{ id: "WEDDING RING", group: 222, label: "WEDDING RING", level: 1, color: "green" },
{ id: "POWER", group: 223, label: "POWER", level: 1, color: "green" },
{ id: "ADAM", group: 224, label: "ADAM", level: 1, color: "green" },
{ id: "ADAM'S APPLE", group: 225, label: "ADAM'S APPLE", level: 1, color: "green" },
{ id: "SOLOMON", group: 226, label: "SOLOMON", level: 1, color: "green" },
{ id: "TIN", group: 227, label: "TIN", level: 1, color: "green" },
{ id: "APPLEJACK", group: 228, label: "APPLEJACK", level: 1, color: "green" },
{ id: "TWO", group: 229, label: "TWO", level: 1, color: "green" },
{ id: "GREEN BUILDING", group: 230, label: "GREEN BUILDING", level: 1, color: "green" },
{ id: "AVENGERS: ENDGAME", group: 231, label: "AVENGERS: ENDGAME", level: 1, color: "green" },
{ id: "TIME TRAVEL", group: 232, label: "TIME TRAVEL", level: 1, color: "green" },
{ id: "JACK BLACK", group: 233, label: "JACK BLACK", level: 1, color: "green" },
{ id: "DAVY JONES", group: 234, label: "DAVY JONES", level: 1, color: "green" },
{ id: "BISHOP", group: 235, label: "BISHOP", level: 1, color: "green" },
{ id: "CHEMICAL X", group: 236, label: "CHEMICAL X", level: 1, color: "green" },
{ id: "TWILIGHT SPARKLE", group: 237, label: "TWILIGHT SPARKLE", level: 1, color: "green" },
{ id: "MERRY", group: 238, label: "MERRY", level: 1, color: "green" },
{ id: "SUPERGIRL", group: 239, label: "SUPERGIRL", level: 1, color: "green" },
{ id: "BACK TO THE FUTURE", group: 240, label: "BACK TO THE FUTURE", level: 1, color: "green" },
{ id: "GRANNY SMITH", group: 241, label: "GRANNY SMITH", level: 1, color: "green" },
{ id: "CARDINAL", group: 242, label: "CARDINAL", level: 1, color: "green" },
{ id: "BLACKBEARD", group: 243, label: "BLACKBEARD", level: 1, color: "green" },
{ id: "GOOGLE", group: 244, label: "GOOGLE", level: 1, color: "green" },
{ id: "MOCKINGJAY", group: 245, label: "MOCKINGJAY", level: 1, color: "green" },
{ id: "A WHOLE NEW WORLD", group: 246, label: "A WHOLE NEW WORLD", level: 1, color: "green" },
{ id: "PRINCE ALI", group: 247, label: "PRINCE ALI", level: 1, color: "green" },
{ id: "007", group: 248, label: "007", level: 1, color: "green" },
{ id: "SEVEN", group: 249, label: "SEVEN", level: 1, color: "green" },
{ id: "LEONARDO", group: 250, label: "LEONARDO", level: 1, color: "green" },
{ id: "FRIEND LIKE ME", group: 251, label: "FRIEND LIKE ME", level: 1, color: "green" },
{ id: "GEMINI", group: 252, label: "GEMINI", level: 1, color: "green" },
{ id: "STATA CENTER", group: 253, label: "STATA CENTER", level: 1, color: "green" },
{ id: "STAR-SPANGLED BANNER", group: 254, label: "STAR-SPANGLED BANNER", level: 1, color: "green" },
{ id: "TRANSFORMERS", group: 255, label: "TRANSFORMERS", level: 1, color: "green" },
{ id: "SPARROW", group: 256, label: "SPARROW", level: 1, color: "green" },
{ id: "BARBARA", group: 257, label: "BARBARA", level: 1, color: "green" },
{ id: "BOOKSPACE", group: 258, label: "BOOKSPACE", level: 1, color: "green" },
{ id: "HOLIDAY FOREST", group: 259, label: "HOLIDAY FOREST", level: 1, color: "green" },
{ id: "BRASS RAT", group: 260, label: "BRASS RAT", level: 1, color: "green" },
{ id: "WHEEL OF FORTUNE", group: 261, label: "WHEEL OF FORTUNE", level: 1, color: "green" },
{ id: "STRAWBERRY", group: 262, label: "STRAWBERRY", level: 1, color: "green" },
{ id: "CAPTAIN HOOK", group: 263, label: "CAPTAIN HOOK", level: 1, color: "green" },
{ id: "ARAGORN", group: 264, label: "ARAGORN", level: 1, color: "green" },
{ id: "JAMES BOND", group: 265, label: "JAMES BOND", level: 1, color: "green" },
{ id: "THOMAS", group: 266, label: "THOMAS", level: 1, color: "green" },
{ id: "HIEROPHANT", group: 267, label: "HIEROPHANT", level: 1, color: "green" },
{ id: "EMILY", group: 268, label: "EMILY", level: 1, color: "green" },
{ id: "STRENGTH", group: 269, label: "STRENGTH", level: 1, color: "green" },
{ id: "SUGAR", group: 270, label: "SUGAR", level: 1, color: "green" },
{ id: "THE THREE APPLES", group: 271, label: "THE THREE APPLES", level: 1, color: "green" },
{ id: "GOLDEN DELICIOUS", group: 272, label: "GOLDEN DELICIOUS", level: 1, color: "green" },
{ id: "GRUMPY", group: 273, label: "GRUMPY", level: 1, color: "green" },
{ id: "SNOWFLAKE", group: 274, label: "SNOWFLAKE", level: 1, color: "green" },
{ id: "GORDON", group: 275, label: "GORDON", level: 1, color: "green" },
{ id: "EDWARD", group: 276, label: "EDWARD", level: 1, color: "green" },
{ id: "ZINC", group: 277, label: "ZINC", level: 1, color: "green" },
{ id: "SNOWBALL", group: 278, label: "SNOWBALL", level: 1, color: "green" },
{ id: "MAGICIAN", group: 279, label: "MAGICIAN", level: 1, color: "green" },
{ id: "SPICE", group: 280, label: "SPICE", level: 1, color: "green" },
{ id: "GREEN ARROW", group: 281, label: "GREEN ARROW", level: 1, color: "green" },
{ id: "MYSTIC", group: 282, label: "MYSTIC", level: 1, color: "green" },
{ id: "JAMES", group: 283, label: "JAMES", level: 1, color: "green" },
{ id: "MULAN", group: 284, label: "MULAN", level: 1, color: "green" },
{ id: "CHANCE", group: 285, label: "CHANCE", level: 1, color: "green" },
{ id: "EVE", group: 286, label: "EVE", level: 1, color: "green" },
{ id: "DIME", group: 287, label: "DIME", level: 1, color: "green" },
{ id: "BILL OF RIGHTS", group: 288, label: "BILL OF RIGHTS", level: 1, color: "green" },
{ id: "RED", group: 289, label: "RED", level: 1, color: "green" },
{ id: "MATTHEW", group: 290, label: "MATTHEW", level: 1, color: "green" },
{ id: "SINBAD THE SAILOR", group: 291, label: "SINBAD THE SAILOR", level: 1, color: "green" },
{ id: "WEREWOLF", group: 292, label: "WEREWOLF", level: 1, color: "green" },
{ id: "KING", group: 293, label: "KING", level: 1, color: "green" },
{ id: "HOMER", group: 294, label: "HOMER", level: 1, color: "green" },
{ id: "GREY", group: 295, label: "GREY", level: 1, color: "green" },
{ id: "SUCROSE", group: 296, label: "SUCROSE", level: 1, color: "green" },
{ id: "SESAME OIL", group: 297, label: "SESAME OIL", level: 1, color: "green" },
{ id: "BERT", group: 298, label: "BERT", level: 1, color: "green" },
{ id: "INSTINCT", group: 299, label: "INSTINCT", level: 1, color: "green" },
{ id: "ZEUS", group: 300, label: "ZEUS", level: 1, color: "green" },
{ id: "CHERRY", group: 301, label: "CHERRY", level: 1, color: "green" },
{ id: "BELLA SWAN", group: 302, label: "BELLA SWAN", level: 1, color: "green" },
{ id: "EBAY", group: 303, label: "EBAY", level: 1, color: "green" },
{ id: "JACK", group: 304, label: "JACK", level: 1, color: "green" },
{ id: "BUBBLES", group: 305, label: "BUBBLES", level: 1, color: "green" },
{ id: "KERMIT", group: 306, label: "KERMIT", level: 1, color: "green" },
{ id: "HERMIONE GRANGER", group: 307, label: "HERMIONE GRANGER", level: 1, color: "green" },
{ id: "NEW MOON", group: 308, label: "NEW MOON", level: 1, color: "green" },
{ id: "LIGHT-NANOSECOND", group: 309, label: "LIGHT-NANOSECOND", level: 1, color: "green" },
{ id: "ANDREW", group: 310, label: "ANDREW", level: 1, color: "green" },
{ id: "RAPHAEL", group: 311, label: "RAPHAEL", level: 1, color: "green" },
{ id: "LISA", group: 312, label: "LISA", level: 1, color: "green" },
{ id: "THE FISHERMAN AND THE JINNI", group: 313, label: "THE FISHERMAN AND THE JINNI", level: 1, color: "green" },
{ id: "BILL AND TED", group: 314, label: "BILL AND TED", level: 1, color: "green" },
{ id: "ELMO", group: 315, label: "ELMO", level: 1, color: "green" },
]

var links = [
{ target: "WORLD", source: "MAJOR ARCANA", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WIZARD", source: "SIRIUS BLACK", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TECH COMPANY", source: "BAIDU", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "LEGOLAS", source: "ELF", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PENNY PARK", source: "MIT MYSTERY HUNT", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "RESISTOR COLOR", source: "BROWN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "QUARTER", source: "COIN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SILVER", source: "RESISTOR COLOR", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "ONE PIECE", source: "ONE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MUSHU", source: "DRAGON", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MONOPOLY", source: "GO", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "ONE", source: "NUMBER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "ZATANNA", source: "DC SUPER HERO GIRLS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "STRAWBERRY FIELDS", source: "JOHN LENNON", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "GO TO JAIL", source: "GO", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "ROBIN HOOD", source: "ARCHER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "VENTI", source: "STARBUCKS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "LEO", source: "ASTROLOGY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "XIAOMI", source: "TECH COMPANY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "POWERPUFF GIRLS", source: "BUTTERCUP", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MIT", source: "GREAT DOME", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "POWERPUFF GIRLS", source: "GIRL", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SIRIUS BLACK", source: "BLACK", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "VALOR", source: "POKEMON GO", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TENCENT", source: "TECH COMPANY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "ELF", source: "DUNGEONS & DRAGONS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PUFF THE MAGIC DRAGON", source: "DRAGON", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "ROBERT PATTINSON", source: "CEDRIC DIGGORY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PENNY", source: "COIN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SAM", source: "FELLOWSHIP", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "NEO", source: "KEANU REEVES", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SESAME STREET", source: "SESAME", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THE HUNGER GAMES", source: "PRESIDENT SNOW", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PRIEST", source: "LOVE LETTER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SHAZAM", source: "MERCURY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "BARTHOLOMEW", source: "APOSTLE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "HOBBIT", source: "FRODO", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PETER PAN", source: "PETER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SILVER", source: "LONG JOHN SILVER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THOMAS THE TANK ENGINE", source: "PERCY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THOMAS THE TANK ENGINE", source: "SIR TOPHAM HATT", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "UNITED STATES", source: "MAYFLOWER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "STAR", source: "SIRIUS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THE WIZARD OF OZ", source: "DOROTHY GALE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SPACE PROGRAM", source: "MERCURY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "BIRD", source: "BIG BIRD", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THE LORD OF THE RINGS", source: "FELLOWSHIP", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PHILIP", source: "APOSTLE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "GALE", source: "DOROTHY GALE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SIMPSONS", source: "BARTHOLOMEW", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THE LAST SUPPER", source: "JESUS CHRIST", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "STAR", source: "MAJOR ARCANA", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WEDDING", source: "FLOWER GIRL", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TECH COMPANY", source: "APPLE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "NINJA TURTLE", source: "DONATELLO", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SHAZAM", source: "ACHILLES", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THE HUNGER GAMES", source: "DYSTOPIA", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "ORANGE", source: "FRUIT", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "RESISTOR COLOR", source: "BLACK", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SHAZAM", source: "HERCULES", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "DYSTOPIA", source: "BRAVE NEW WORLD", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "POKEMON GO", source: "GO", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "ROBERT PATTINSON", source: "NEIL", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "FLOWER POWER", source: "FLOWER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PIPPIN", source: "FELLOWSHIP", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "JUDAS", source: "JESUS CHRIST", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PERCY WEASLEY", source: "PERCY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PENNY PARK", source: "PENNY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "ROBIN", source: "BATMAN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "DISNEY", source: "ALADDIN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "DC", source: "BATGIRL", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "LEGOLAS", source: "FELLOWSHIP", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SUN", source: "PRINCESS CELESTIA", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PRINCESS LUNA", source: "PRINCESS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WEDDING", source: "GROOM", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MONOPOLY", source: "COMMUNITY CHEST", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WISDOM", source: "ATHENA", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THE CREATION OF ADAM", source: "SISTINE CHAPEL", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "VENTI", source: "GENSHIN IMPACT", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SUN", source: "MAJOR ARCANA", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "UNITED STATES", source: "JOHNNY APPLESEED", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MOON", source: "MAJOR ARCANA", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "BATMAN", source: "BATGIRL", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "VAMPIRE", source: "COUNT VON COUNT", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TRIFORCE", source: "COURAGE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "FELLOWSHIP", source: "BOROMIR", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SMOOT", source: "MEASUREMENT", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "FORTUNE FAVORS THE BOLD", source: "COURAGE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PRINCE", source: "LOVE LETTER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "RED DELICIOUS", source: "APPLE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "NUMBER", source: "NINETEEN EIGHTY-FOUR", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SNOW", source: "PRESIDENT SNOW", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "RING", source: "7 RINGS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SIRIUS BLACK", source: "SIRIUS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THE LORD OF THE RINGS", source: "SMAUG", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WHITE", source: "GANDALF", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WIZARD", source: "MERLIN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SESAME STREET", source: "GROVER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SILVER", source: "METAL", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PERPIW", source: "MIT MYSTERY HUNT", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TIM THE BEAVER", source: "MIT", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "NINJA TURTLE", source: "MICHELANGELO", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TWILIGHT", source: "ECLIPSE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TWILIGHT", source: "EDWARD CULLEN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "METAL", source: "GOLD", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "DUNGEONS & DRAGONS", source: "DRAGON", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SNOW WHITE", source: "DOC", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TWILIGHT", source: "BREAKING DAWN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "FORTUNE TELLING", source: "FORTUNE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SLEEPY", source: "DWARF", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WONDER WOMAN", source: "DC", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TED", source: "KEANU REEVES", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "COPPER", source: "BRASS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "ROBERT PATTINSON", source: "EDWARD CULLEN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "JACOB BLACK", source: "BLACK", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SAGITTARIUS", source: "ASTROLOGY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WORLD", source: "ATLAS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SPIKE", source: "DRAGON", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "POPE", source: "CATHOLIC CHURCH", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "OPEN SESAME", source: "ARABIAN NIGHTS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "POWERPUFF GIRLS", source: "MOJO JOJO", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SESAME", source: "OPEN SESAME", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SAM", source: "HOBBIT", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WIZARD", source: "GANDALF", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WHITE", source: "BLUE-EYES WHITE DRAGON", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "HOBBIT", source: "HALFLING", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TALL", source: "STARBUCKS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "VAMPIRE", source: "EDWARD CULLEN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SESAME STREET", source: "OSCAR", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "ORANGE", source: "BLOSSOM", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "GREEK MYTHOLOGY", source: "ACHILLES", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MY LITTLE PONY", source: "LAUREN FAUST", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MONOPOLY", source: "HASBRO", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WIZARD", source: "DUMBLEDORE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "JOHN WICK", source: "JOHN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THE PRINCESS BRIDE", source: "PRINCESS BUTTERCUP", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SUNFLOWER", source: "FLOWER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "RING", source: "ONE RING", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SNOW WHITE", source: "DISNEY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MERLIN", source: "KING ARTHUR", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WEDDING", source: "BRIDE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SPACE PROGRAM", source: "APOLLO", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WIZARD", source: "BELLATRIX BLACK", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "KATNISS EVERDEEN", source: "ARCHER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THE LORD OF THE RINGS", source: "RING", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "FORTUNE COOKIE", source: "FORTUNE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "UNITED STATES", source: "GEORGE WASHINGTON", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PIRATE", source: "JACK SPARROW", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "NICKEL", source: "METAL", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WHITE", source: "RESISTOR COLOR", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "ARIANA GRANDE", source: "7 RINGS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PUFF THE MAGIC DRAGON", source: "PUFF", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PIRATE", source: "LUFFY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "DECLARATION OF INDEPENDENCE", source: "CONSTITUTION", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THREE", source: "NUMBER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "JESUS CHRIST", source: "APOSTLE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MEASUREMENT", source: "BATMAN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SESAME STREET", source: "COOKIE MONSTER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "LION", source: "COWARDLY LION", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "VAMPIRE", source: "DRACULA", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "RESISTOR COLOR", source: "BLUE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "FACEBOOK", source: "BYTEDANCE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "GRANDE", source: "ARIANA GRANDE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THE HANDMAID'S TALE", source: "HANDMAID", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "STARBUCKS", source: "STAR", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PIPPIN", source: "HOBBIT", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TIN MAN", source: "THE WIZARD OF OZ", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PETER", source: "APOSTLE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "DOC BROWN", source: "DOC", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PETER PAN", source: "DISNEY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MAGIC THE GATHERING", source: "HASBRO", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SUPERMAN", source: "DC", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TECH COMPANY", source: "BYTEDANCE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MIT", source: "KRESGE CENTER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "VAMPIRE", source: "TWILIGHT", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "FORTUNE TELLING", source: "ASTROLOGY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SESAME STREET", source: "ERNIE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "RESISTOR COLOR", source: "GOLD", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SISTINE CHAPEL", source: "MICHELANGELO", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "RESISTOR COLOR", source: "GREEN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "POWERPUFF GIRLS", source: "EVERYTHING NICE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "GIMLI", source: "DWARF", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SIMPSONS", source: "MARGE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "HERCULES", source: "GREEK MYTHOLOGY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "METAL", source: "COPPER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MONOPOLY", source: "FREE PARKING", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WIZARD", source: "PERCY WEASLEY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WONDER WOMAN", source: "DC SUPER HERO GIRLS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WEDDING RING", source: "WEDDING", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "POWERPUFF GIRLS", source: "POWER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "ADAM'S APPLE", source: "ADAM", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "LAUREN FAUST", source: "DC SUPER HERO GIRLS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SOLOMON", source: "SHAZAM", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TIN MAN", source: "TIN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "APPLEJACK", source: "APPLE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TWO", source: "NUMBER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MIT", source: "GREEN BUILDING", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TWILIGHT", source: "JACOB BLACK", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "GREEK MYTHOLOGY", source: "APOLLO", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TIME TRAVEL", source: "AVENGERS: ENDGAME", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "JACK BLACK", source: "BLACK", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PIRATE", source: "DAVY JONES", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "CATHOLIC CHURCH", source: "BISHOP", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THE HUNGER GAMES", source: "KATNISS EVERDEEN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THE CREATION OF ADAM", source: "ADAM", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "POWERPUFF GIRLS", source: "CHEMICAL X", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SAGITTARIUS", source: "ARCHER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PRINCESS CELESTIA", source: "MY LITTLE PONY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "GIMLI", source: "FELLOWSHIP", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TWILIGHT SPARKLE", source: "MY LITTLE PONY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MERRY", source: "FELLOWSHIP", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SUPERMAN", source: "SUPERGIRL", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TIME TRAVEL", source: "BACK TO THE FUTURE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "GRANNY SMITH", source: "APPLE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "CARDINAL", source: "BIRD", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PIRATE", source: "BLACKBEARD", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PRINCESS", source: "PRINCE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "GOOGLE", source: "BAIDU", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MOCKINGJAY", source: "BIRD", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "FORTUNE FAVORS THE BOLD", source: "FORTUNE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "ALADDIN", source: "A WHOLE NEW WORLD", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "DUNGEONS & DRAGONS", source: "CONSTITUTION", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SMOOT", source: "MIT", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PRINCE ALI", source: "ALADDIN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "DWARF", source: "DUNGEONS & DRAGONS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "DC", source: "BATMAN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "GREEN BUILDING", source: "GREEN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SEVEN", source: "007", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "NINJA TURTLE", source: "LEONARDO", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PRINCESS BUTTERCUP", source: "BUTTERCUP", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "FRIEND LIKE ME", source: "ALADDIN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SPACE PROGRAM", source: "GEMINI", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "STATA CENTER", source: "MIT", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "UNITED STATES", source: "STAR-SPANGLED BANNER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TRANSFORMERS", source: "HASBRO", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SPARROW", source: "JACK SPARROW", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MAYFLOWER", source: "FLOWER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "GENSHIN IMPACT", source: "BARBARA", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MIT MYSTERY HUNT", source: "BOOKSPACE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "ONE RING", source: "ONE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SEVEN", source: "7 RINGS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MIT MYSTERY HUNT", source: "HOLIDAY FOREST", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "STARBUCKS", source: "GRANDE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "QUARTER", source: "GEORGE WASHINGTON", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SHAZAM", source: "ATLAS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WIZARD", source: "CEDRIC DIGGORY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MIT", source: "BRASS RAT", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WHEEL OF FORTUNE", source: "MAJOR ARCANA", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "UNITED STATES", source: "DECLARATION OF INDEPENDENCE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TWILIGHT SPARKLE", source: "TWILIGHT", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "ARABIAN NIGHTS", source: "ALADDIN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "ARCHER", source: "APOLLO", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "STRAWBERRY", source: "FRUIT", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PIRATE", source: "CAPTAIN HOOK", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "FELLOWSHIP", source: "ARAGORN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "FLOWER", source: "BLOSSOM", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SNOW WHITE", source: "SLEEPY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MY LITTLE PONY", source: "GRANNY SMITH", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "JAMES BOND", source: "007", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THOMAS THE TANK ENGINE", source: "THOMAS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MAJOR ARCANA", source: "HIEROPHANT", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THOMAS THE TANK ENGINE", source: "EMILY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "STRENGTH", source: "MAJOR ARCANA", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PETER PAN", source: "CAPTAIN HOOK", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SUGAR", source: "POWERPUFF GIRLS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "BLUE-EYES WHITE DRAGON", source: "BLUE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THE THREE APPLES", source: "ARABIAN NIGHTS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "GOLDEN DELICIOUS", source: "APPLE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "GRUMPY", source: "DWARF", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WIZARD", source: "THE WIZARD OF OZ", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "FRUIT", source: "APPLE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SNOWFLAKE", source: "SNOW", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "GORDON", source: "BATGIRL", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WEDDING RING", source: "RING", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PIRATE", source: "LONG JOHN SILVER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THOMAS THE TANK ENGINE", source: "EDWARD", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TRIFORCE", source: "POWER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "ZINC", source: "METAL", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SNOWBALL", source: "SNOW", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THE HUNGER GAMES", source: "MOCKINGJAY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TECH COMPANY", source: "ALI BABA", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "POWER", source: "FLOWER POWER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "ONE PIECE", source: "LUFFY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SMAUG", source: "DRAGON", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "COURAGE", source: "BRAVE NEW WORLD", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MAJOR ARCANA", source: "MAGICIAN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THE LAST SUPPER", source: "APOSTLE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TIN", source: "METAL", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PRIEST", source: "CATHOLIC CHURCH", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "JOHN", source: "APOSTLE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MERRY", source: "HOBBIT", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SPICE", source: "POWERPUFF GIRLS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "GREEN ARROW", source: "GREEN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "POKEMON GO", source: "MYSTIC", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "METAL", source: "MERCURY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SUPERGIRL", source: "DC", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WISDOM", source: "TRIFORCE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TECH COMPANY", source: "FACEBOOK", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THOMAS THE TANK ENGINE", source: "JAMES", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "JUDAS", source: "APOSTLE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "DWARF", source: "DOC", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "KEANU REEVES", source: "JOHN WICK", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "STAR-SPANGLED BANNER", source: "STAR", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MUSHU", source: "MULAN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MONOPOLY", source: "CHANCE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "EVE", source: "ADAM", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "DIME", source: "COIN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MY LITTLE PONY", source: "APPLEJACK", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "CONSTITUTION", source: "BILL OF RIGHTS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "DOC BROWN", source: "BROWN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "RED DELICIOUS", source: "RED", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "GREEK MYTHOLOGY", source: "ATLAS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MATTHEW", source: "APOSTLE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SPARROW", source: "BIRD", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PRINCESS CELESTIA", source: "PRINCESS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "POWERPUFF GIRLS", source: "BLOSSOM", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THE HANDMAID'S TALE", source: "DYSTOPIA", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TECH COMPANY", source: "GOOGLE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PRINCESS", source: "LOVE LETTER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SILVER", source: "JUDAS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THE LAST SUPPER", source: "LEONARDO", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MAJOR ARCANA", source: "FORTUNE TELLING", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SESAME STREET", source: "COUNT VON COUNT", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MIT MYSTERY HUNT", source: "COIN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PUFF", source: "POWERPUFF GIRLS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "STRAWBERRY FIELDS", source: "STRAWBERRY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "UNITED STATES", source: "BILL OF RIGHTS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PRINCE ALI", source: "PRINCE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "FLOWER GIRL", source: "FLOWER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SINBAD THE SAILOR", source: "ARABIAN NIGHTS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "POWERPUFF GIRLS", source: "LAUREN FAUST", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WEREWOLF", source: "TWILIGHT", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WHEEL OF FORTUNE", source: "FORTUNE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "LION", source: "LEO", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "CATHOLIC CHURCH", source: "CARDINAL", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SEVEN", source: "NUMBER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THE CREATION OF ADAM", source: "MICHELANGELO", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "GEMINI", source: "ASTROLOGY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THE THREE APPLES", source: "APPLE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "STRENGTH", source: "DUNGEONS & DRAGONS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SPIKE", source: "MY LITTLE PONY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "LEGOLAS", source: "ARCHER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "LOVE LETTER", source: "KING", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "BATGIRL", source: "BARBARA", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PRINCESS BUTTERCUP", source: "PRINCESS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SIMPSONS", source: "HOMER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "RED DELICIOUS", source: "GOLDEN DELICIOUS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "RESISTOR COLOR", source: "GREY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "GREEN ARROW", source: "ARCHER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MIT", source: "ATHENA", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "DRAGON", source: "BLUE-EYES WHITE DRAGON", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THE HUNGER GAMES", source: "GALE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SUGAR", source: "SUCROSE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "LOVE LETTER", source: "HANDMAID", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "LONG JOHN SILVER", source: "JOHN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "UNITED STATES", source: "CONSTITUTION", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "BRASS RAT", source: "BRASS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SESAME OIL", source: "SESAME", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SESAME STREET", source: "BERT", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "NINETEEN EIGHTY-FOUR", source: "DYSTOPIA", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "POKEMON GO", source: "INSTINCT", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WISDOM", source: "SOLOMON", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "HASBRO", source: "DUNGEONS & DRAGONS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "ZEUS", source: "GREEK MYTHOLOGY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "FRUIT", source: "CHERRY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THE WIZARD OF OZ", source: "COWARDLY LION", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "GREY", source: "GANDALF", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WORLD", source: "BRAVE NEW WORLD", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SESAME STREET", source: "BIG BIRD", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TWILIGHT", source: "BELLA SWAN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "XIAOMI", source: "APPLE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "JAMES", source: "APOSTLE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THOMAS THE TANK ENGINE", source: "GORDON", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SUNFLOWER", source: "SUN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WORLD", source: "A WHOLE NEW WORLD", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "ZEUS", source: "SHAZAM", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SUPERGIRL", source: "DC SUPER HERO GIRLS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "ROBERT PATTINSON", source: "BATMAN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "VALOR", source: "COURAGE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "RESISTOR COLOR", source: "ORANGE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "EBAY", source: "ALI BABA", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "ROBIN", source: "BIRD", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "JACK BLACK", source: "JACK", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "RESISTOR COLOR", source: "RED", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "DOC BROWN", source: "BACK TO THE FUTURE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "JAMES BOND", source: "JAMES", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "CHERRY", source: "BLOSSOM", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SUN", source: "ECLIPSE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PRINCESS LUNA", source: "MOON", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MOON", source: "ECLIPSE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "APPLE", source: "ADAM'S APPLE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "GIRL", source: "BATGIRL", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "POWERPUFF GIRLS", source: "BUBBLES", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "POPE", source: "HIEROPHANT", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "JOHNNY APPLESEED", source: "APPLE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "ZINC", source: "BRASS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WISDOM", source: "DUNGEONS & DRAGONS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MEASUREMENT", source: "KERMIT", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WIZARD", source: "HERMIONE GRANGER", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "NEW MOON", source: "MOON", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "ZATANNA", source: "DC", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SNOW WHITE", source: "GRUMPY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SNOW WHITE", source: "SNOW", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MEASUREMENT", source: "LIGHT-NANOSECOND", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "GIRL", source: "FLOWER GIRL", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "GREEK MYTHOLOGY", source: "ATHENA", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THREE", source: "THE THREE APPLES", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "APOSTLE", source: "ANDREW", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MIT MYSTERY HUNT", source: "MIT", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SHAZAM", source: "DC", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "RAPHAEL", source: "NINJA TURTLE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SESAME STREET", source: "KERMIT", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SIMPSONS", source: "LISA", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "PRINCESS LUNA", source: "MY LITTLE PONY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "ADAM", source: "ADAM", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "GREEN ARROW", source: "DC", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WIZARD", source: "MAGICIAN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "GANDALF", source: "FELLOWSHIP", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "NICKEL", source: "COIN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TECH COMPANY", source: "EBAY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "JACK SPARROW", source: "JACK", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "BLACK", source: "BELLATRIX BLACK", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "HALFLING", source: "DUNGEONS & DRAGONS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MULAN", source: "DISNEY", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SUN", source: "STAR", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THE FISHERMAN AND THE JINNI", source: "ARABIAN NIGHTS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "WHITE", source: "SNOW WHITE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TIME TRAVEL", source: "BILL AND TED", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "GOLDEN DELICIOUS", source: "GOLD", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TED", source: "BILL AND TED", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "DECLARATION OF INDEPENDENCE", source: "BILL OF RIGHTS", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "ARABIAN NIGHTS", source: "ALI BABA", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TENCENT", source: "DIME", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "JOHN LENNON", source: "JOHN", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "DC SUPER HERO GIRLS", source: "BATGIRL", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MY LITTLE PONY", source: "HASBRO", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "FRODO", source: "FELLOWSHIP", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "MONOPOLY", source: "GO TO JAIL", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SESAME STREET", source: "ELMO", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "SUCROSE", source: "GENSHIN IMPACT", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "TWILIGHT", source: "NEW MOON", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "THOMAS", source: "APOSTLE", color: "rgba(50,50,50,0.5)", strength: 0.3 },
{ target: "KING ARTHUR", source: "KING", color: "rgba(50,50,50,0.5)", strength: 0.3 },
]
